//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeLi.SkillPoint.App.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeLi.SkillPoint.App.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apples.
        /// </summary>
        internal static string Apples {
            get {
                return ResourceManager.GetString("Apples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Apples xmlns:xsi=&quot;&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&quot; xmlns:xsd=&quot;&quot;http://www.w3.org/2001/XMLSchema&quot;&quot;&gt;.
        /// </summary>
        internal static string ApplesNode {
            get {
                return ResourceManager.GetString("ApplesNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/Apples&gt;.
        /// </summary>
        internal static string ApplesNodeEnd {
            get {
                return ResourceManager.GetString("ApplesNodeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;ArrayOfApple xmlns:xsi=&quot;&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&quot; xmlns:xsd=&quot;&quot;http://www.w3.org/2001/XMLSchema&quot;&quot;&gt;.
        /// </summary>
        internal static string ArrayOfAppleNode {
            get {
                return ResourceManager.GetString("ArrayOfAppleNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;/ArrayOfApple&gt;.
        /// </summary>
        internal static string ArrayOfAppleNodeEnd {
            get {
                return ResourceManager.GetString("ArrayOfAppleNodeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big Endian.
        /// </summary>
        internal static string BigEndian {
            get {
                return ResourceManager.GetString("BigEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KeLi.SkillPoint.ConsoleApp.exe.config.
        /// </summary>
        internal static string ConfigPath {
            get {
                return ResourceManager.GetString("ConfigPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectLog.
        /// </summary>
        internal static string ConnectLog {
            get {
                return ResourceManager.GetString("ConnectLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnSql.
        /// </summary>
        internal static string ConnStrKeyName {
            get {
                return ResourceManager.GetString("ConnStrKeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectionStrings.
        /// </summary>
        internal static string ConnStrValueName {
            get {
                return ResourceManager.GetString("ConnStrValueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=.;DataBase=StudentMgt;Uid=sa;Pwd=123789.
        /// </summary>
        internal static string CrErrorConnStr {
            get {
                return ResourceManager.GetString("CrErrorConnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server=.;DataBase=StudentMgt;Uid=sa;Pwd=123456.
        /// </summary>
        internal static string CrRightConnStr {
            get {
                return ResourceManager.GetString("CrRightConnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denny.
        /// </summary>
        internal static string Denny {
            get {
                return ResourceManager.GetString("Denny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mm:ss.ffff.
        /// </summary>
        internal static string ExactPartTimeFormat {
            get {
                return ResourceManager.GetString("ExactPartTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 123456789.
        /// </summary>
        internal static string HashCodeTest {
            get {
                return ResourceManager.GetString("HashCodeTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack.
        /// </summary>
        internal static string Jack {
            get {
                return ResourceManager.GetString("Jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jim.
        /// </summary>
        internal static string Jim {
            get {
                return ResourceManager.GetString("Jim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John.
        /// </summary>
        internal static string John {
            get {
                return ResourceManager.GetString("John", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juan.
        /// </summary>
        internal static string Juan {
            get {
                return ResourceManager.GetString("Juan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little Endian.
        /// </summary>
        internal static string LittleEndian {
            get {
                return ResourceManager.GetString("LittleEndian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mike.
        /// </summary>
        internal static string Mike {
            get {
                return ResourceManager.GetString("Mike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nino.
        /// </summary>
        internal static string Nino {
            get {
                return ResourceManager.GetString("Nino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Interned.
        /// </summary>
        internal static string NotInterned {
            get {
                return ResourceManager.GetString("NotInterned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Num Sum: .
        /// </summary>
        internal static string NumSum {
            get {
                return ResourceManager.GetString("NumSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phil.
        /// </summary>
        internal static string Phil {
            get {
                return ResourceManager.GetString("Phil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (int)1.1/1.0={0}.
        /// </summary>
        internal static string PuFormula1 {
            get {
                return ResourceManager.GetString("PuFormula1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (int)(1.1/1.0)={0}.
        /// </summary>
        internal static string PuFormula2 {
            get {
                return ResourceManager.GetString("PuFormula2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: Casting priority than arithmetic precedence..
        /// </summary>
        internal static string PuHigh {
            get {
                return ResourceManager.GetString("PuHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result: Casting priority precedence than the arithmetic operation..
        /// </summary>
        internal static string PuLow {
            get {
                return ResourceManager.GetString("PuLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM StudentInfo.
        /// </summary>
        internal static string QueryStudentSql {
            get {
                return ResourceManager.GetString("QueryStudentSql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stack: .
        /// </summary>
        internal static string StackMsg {
            get {
                return ResourceManager.GetString("StackMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentInfo.
        /// </summary>
        internal static string StudentInfo {
            get {
                return ResourceManager.GetString("StudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No{0}.
        /// </summary>
        internal static string SuNo {
            get {
                return ResourceManager.GetString("SuNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} goes to the bathroom, the time is: {1}.
        /// </summary>
        internal static string SuTime {
            get {
                return ResourceManager.GetString("SuTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy-MM-dd-HH-mm.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time passes....
        /// </summary>
        internal static string TimePass {
            get {
                return ResourceManager.GetString("TimePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World.
        /// </summary>
        internal static string World {
            get {
                return ResourceManager.GetString("World", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsd.
        /// </summary>
        internal static string XsdKey {
            get {
                return ResourceManager.GetString("XsdKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema.
        /// </summary>
        internal static string XsdValue {
            get {
                return ResourceManager.GetString("XsdValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xsi.
        /// </summary>
        internal static string XsiKey {
            get {
                return ResourceManager.GetString("XsiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://www.w3.org/2001/XMLSchema-instance.
        /// </summary>
        internal static string XsiValue {
            get {
                return ResourceManager.GetString("XsiValue", resourceCulture);
            }
        }
    }
}
